import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Nav";
import Footer from "./components/Footer/Footer";
import Contact from "./components/Contact/Contact";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.className}>
        <Navbar />
        <div className="container">
          {children}
        </div>
        <Contact />
        <Footer />
      </body>
    </html >
  );
}
